algoritmo "funcoes"
var
   n1, n2, res : inteiro
/////////////////////////////
funcao soma(a, b : inteiro) : inteiro
//var
//   s : inteiro
inicio
      //s <- a + b
      //retorne s
      retorne a + b
fimfuncao
/////////////////////////////
inicio
      escreva("digite um numero: ")
      leia(n1)
      escreva("digite outro numero: ")
      leia(n2)
      //res <- soma(n1, n2)
      //escreval("a soma é",res)
      escreva("a soma é",soma(n1,n2))
fimalgoritmo