a = input('Digite algo')
print('Tipo primitivo desse valo é', type(a))
print('Só tem espaços?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Está em maiúsculas', a.isupper())
print('Esta em minusculas?', a.islower())
print('Está capitalizanada?', a.istitle())
